### ISSUE TITLE
运行时报错，pymem.exception.WinAPIError: Windows api error, error_code: 299

### ISSUE THREAD

**Issue by ruitong1983** [f13T2ach/WxMsgDump#10]
Traceback (most recent call last):
  File "D:\Software\Python\Python3810\lib\site-packages\pymem\__init__.py", line 501, in read_bytes
    value = pymem.memory.read_bytes(self.process_handle, address, length)
  File "D:\Software\Python\Python3810\lib\site-packages\pymem\memory.py", line 97, in read_bytes
    return read_ctype(handle, address, (byte * ctypes.c_char)(), get_py_value=False).raw
  File "D:\Software\Python\Python3810\lib\site-packages\pymem\memory.py", line 148, in read_ctype
    raise pymem.exception.WinAPIError(error_code)
pymem.exception.WinAPIError: Windows api error, error_code: 299

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\10_Code\LLM\WXChat\WxMsgDump-main\Main.py", line 172, in <module>
    main()
  File "E:\10_Code\LLM\WXChat\WxMsgDump-main\Main.py", line 41, in main
    ret = GetWeChatInfo.main()
  File "E:\10_Code\LLM\WXChat\WxMsgDump-main\GetWeChatInfo.py", line 101, in main
    wxid,wxprofile,aesKey = getUserBasicInfo(p,base)
  File "E:\10_Code\LLM\WXChat\WxMsgDump-main\GetWeChatInfo.py", line 58, in getUserBasicInfo
    WXID = p.read_bytes(wxid_addr, int_wxid_len)
  File "D:\Software\Python\Python3810\lib\site-packages\pymem\__init__.py", line 503, in read_bytes
    raise pymem.exception.MemoryReadError(address, length, e.error_code)
pymem.exception.MemoryReadError: Could not read memory at: 0, length: 695 - GetLastError: 299
0 695

进程已结束,退出代码1

**Comment by Sher2305** [comment]
你好，我也遇到了这个问题，该如何解决呢？
