### ISSUE TITLE
3.9.6.33版本出现报错

### ISSUE THREAD

**Issue by Dugege007** [f13T2ach/WxMsgDump#15]
已按照之前的issue将to_bytes改为8

以下是cmd窗口中的消息：

Microsoft Windows [版本 10.0.19045.3208]
(c) Microsoft Corporation。保留所有权利。

D:\GithubRepository\Download\WxMsgDump-main>python Main.py
WxMsgDumpV1.1 | 微信聊天记录导出

Copyright(c) UvgenTechno 2023 Authorized
----------------------------------------
[+]Follow me on Github: https://github.com/f13T2ach/WxMsgDump
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\pymem\__init__.py", line 501, in read_bytes
    value = pymem.memory.read_bytes(self.process_handle, address, length)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\pymem\memory.py", line 97, in read_bytes
    return read_ctype(handle, address, (byte * ctypes.c_char)(), get_py_value=False).raw
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\pymem\memory.py", line 148, in read_ctype
    raise pymem.exception.WinAPIError(error_code)
pymem.exception.WinAPIError: Windows api error, error_code: 299

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\GithubRepository\Download\WxMsgDump-main\Main.py", line 172, in <module>
    main()
  File "D:\GithubRepository\Download\WxMsgDump-main\Main.py", line 41, in main
    ret =  GetWeChatInfo.main()
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GithubRepository\Download\WxMsgDump-main\GetWeChatInfo.py", line 100, in main
    wxid,wxprofile,aesKey = getUserBasicInfo(p,base)
                            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GithubRepository\Download\WxMsgDump-main\GetWeChatInfo.py", line 57, in getUserBasicInfo
    WXID = p.read_bytes(wxid_addr, int_wxid_len)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\pymem\__init__.py", line 503, in read_bytes
    raise pymem.exception.MemoryReadError(address, length, e.error_code)
pymem.exception.MemoryReadError: Could not read memory at: 0, length: 571 - GetLastError: 299

D:\GithubRepository\Download\WxMsgDump-main>

![image](https://github.com/f13T2ach/WxMsgDump/assets/59428508/14df9fd8-3a84-4065-8dab-c996141bb945)

这个问题有办法解决吗？

**Comment by FF7518** [comment]
我也遇到这个问题，回退一下微信版本好了，我参考了readme里面的第一个链接

**Comment by JoeQinOvO** [comment]
我也是！求解决！！ @f13T2ach 
WxDump的项目我找了很多个，这个是我觉得最好的，今天更新微信之后就搞不了了，求解决

**Comment by rolle0211** [comment]
遇到这个问题回退一下微信版本就行了，对比过回退前后的差异：
base_address = pymem.process.module_from_name(p.process_handle, "wechatwin.dll").lpBaseOfDll
获取到的地址是不一样的，目前不知道什么原因。可以去下载"3.9.2.23"版本的微信，不用卸载现有版本的微信，下载完直接安装就好。
链接：https://pan.quark.cn/s/f37946db41b9

**Comment by JoeQinOvO** [comment]
> 遇到这个问题回退一下微信版本就行了，对比过回退前后的差异： base_address = pymem.process.module_from_name(p.process_handle, "wechatwin.dll").lpBaseOfDll 获取到的地址是不一样的，目前不知道什么原因。可以去下载"3.9.2.23"版本的微信，不用卸载现有版本的微信，下载完直接安装就好。 链接：https://pan.quark.cn/s/f37946db41b9

还是希望找到一个自动寻找基址的办法，重装一个微信有时太麻烦，也有情景下是不能做到的

**Comment by f13T2ach** [comment]
对于这个问题，我建议你先回退微信版本。这可能是因为自动寻找基址的算法失效了。我猜测微信对密钥进行了加密。目前，我在尝试使用dumpkey.exe的寻址算法。
-------- 原始信息 --------发件人： JoeQinOvO ***@***.***> 日期: 2023/9/10  上午12:43  (GMT+08:00) 收件人： f13T2ach/WxMsgDump ***@***.***> 抄送： Sokasne Redmaple ***@***.***>, Mention ***@***.***> 主题： Re: [f13T2ach/WxMsgDump] 3.9.6.33版本出现报错 (Issue #15) 
我也是！求解决！！ @f13T2ach
WxDump的项目我找了很多个，这个是我觉得最好的，今天更新微信之后就搞不了了，求解决

**Comment by JoeQinOvO** [comment]
@f13T2ach 
找到了一个项目，同样是python的，你可以看看
