### ISSUE TITLE
直接双击 出错

### ISSUE THREAD

**Issue by cgisky1980** [f13T2ach/WxMsgDump#2]
```
WxMsgDumpV1.1 | 微信聊天记录导出

Copyright(c) UvgenTechno 2023 Authorized
----------------------------------------
[+]Follow me on Github: https://github.com/f13T2ach/WxMsgDump 正在获取你的个人信息...
Traceback (most recent call last):
  File "pymem\__init__.py", line 469, in read_bytes
  File "pymem\memory.py", line 112, in read_bytes
pymem.exception.WinAPIError: Windows api error, error_code: 299

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Main.py", line 171, in <module>
  File "Main.py", line 41, in main
  File "GetWeChatInfo.py", line 117, in main
  File "GetWeChatInfo.py", line 75, in getUserBasicInfo
  File "pymem\__init__.py", line 471, in read_bytes
pymem.exception.MemoryReadError: Could not read memory at: 1936287587, length: 6 - GetLastError: 299
[373984] Failed to execute script 'Main' due to unhandled exception!
```

**Comment by cgisky1980** [comment]
源码运行也是一样  微信版本3.9.2.13  win10

**Comment by f13T2ach** [comment]
感谢您留下的Issue
**研究**
根据您的反馈，问题的原因是某些情况下微信私钥地址小于搜索到的微信基址，导致偏移后的地址不是微信私钥的实际地址。这是小概率事件，我们**无法获知原因来根本去除它。**
**解决方法**
1.重启微信多次，或者重启您的计算机。这样可以使微信重新申请内存。
2.更新您的微信。
再次感谢您的Issue。

**Comment by Eyion** [comment]
我的闪一下就没了，这个是PC微信的聊天记录查看和备份的？安卓手机的有吗？
