### ISSUE TITLE
gdk编码报错

### ISSUE THREAD

**Issue by Carey81755** [f13T2ach/WxMsgDump#3]
WxMsgDumpV1.1 | 微信聊天记录导出

Copyright(c) UvgenTechno 2023 Authorized
----------------------------------------
[+]Follow me on Github: https://github.com/f13T2ach/WxMsgDump
[+]微信版本：3.9.2.23
[+]微信基址：0x5b1fd99c
[+]数据库密钥：566c77ec2508452e8a6f7c67cc3214ae1280eba53e4749ae98934c3efeb768f1
[+]WXID：wxid_1bq4nog5y24e12
Traceback (most recent call last):
  File "E:\CODE\WxMsgDump-main\Main.py", line 174, in <module>
    main()
  File "E:\CODE\WxMsgDump-main\Main.py", line 52, in main
    if wx_config.read() == 'MyDocument:':
UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 18: illegal multibyte sequence

**Comment by miaoxutao123** [comment]
49行切换编码格式应该可以解决
wx_config = open(os.getenv("SystemDrive") + win_user + '\\AppData\\Roaming\\Tencent\\WeChat\\All Users\\config\\3ebffe94.ini',encoding='gb18030')
