### ISSUE TITLE
报错：TypeError: unsupported operand type(s) for -: 'list' and 'int'

### ISSUE THREAD

**Issue by KMnO4-zx** [f13T2ach/WxMsgDump#5]
WxMsgDumpV1.1 | 微信聊天记录导出

Copyright(c) UvgenTechno 2023 Authorized
----------------------------------------
[+]Follow me on Github: https://github.com/f13T2ach/WxMsgDump
Traceback (most recent call last):
  File "Main.py", line 172, in <module>
    main()
  File "Main.py", line 41, in main
    ret =  GetWeChatInfo.main()
  File "G:\日常文件\datawhale学习\DataWhaleEnglish\WxMsgDump\GetWeChatInfo.py", line 100, in main
    wxid,wxprofile,aesKey = getUserBasicInfo(p,base)
  File "G:\日常文件\datawhale学习\DataWhaleEnglish\WxMsgDump\GetWeChatInfo.py", line 55, in getUserBasicInfo
    int_wxid_len = p.read_int(base_address - 0x44)
TypeError: unsupported operand type(s) for -: 'list' and 'int'

**Comment by bqzzd1** [comment]
重启下微信试试

**Comment by KMnO4-zx** [comment]
嗯嗯，试过之后还是不行。新的报错如下：
Traceback (most recent call last):
  File "Main.py", line 172, in <module>
    main()
  File "Main.py", line 50, in main
    if wx_config.read() == 'MyDocument:':
UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 5: illegal multibyte sequence
PS G:\日常文件\datawhale学习\DataWhaleEnglish\WxMsgDump>

**Comment by KMnO4-zx** [comment]
> 重启下微信试试

嗯嗯，试过之后还是不行。新的报错如下：
Traceback (most recent call last):
File "Main.py", line 172, in
main()
File "Main.py", line 50, in main
if wx_config.read() == 'MyDocument:':
UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 5: illegal multibyte sequence
PS G:\日常文件\datawhale学习\DataWhaleEnglish\WxMsgDump>

**Comment by KMnO4-zx** [comment]
数据库密钥显示出来了
